name: Manual Deploy to Lightsail

on:
  workflow_dispatch: # makes it manual trigger only

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (not strictly needed, but useful for metadata)
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            cd ~/jjm/storefront

            echo ">>> clearing out nextjs cache"
            rm -rf .next

            echo ">>> Pulling latest code"
            git fetch origin main
            git reset --hard origin/main

            echo ">>> Installing deps"
            yarn install --immutable

            echo ">>> Building Next.js app"
            yarn run build

            echo ">>> Reloading app with PM2"
            pm2 restart 1
